# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

flr_to_list <- function(om, advice, year, nstock, nfleet, niter) {
    .Call('_MIME_flr_to_list', PACKAGE = 'MIME', om, advice, year, nstock, nfleet, niter)
}

