# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

attach_attribute <- function(fisheries, attribute, fl, st, attribute_name) {
    .Call('_MixME_attach_attribute', PACKAGE = 'MixME', fisheries, attribute, fl, st, attribute_name)
}

flr_to_list <- function(om, advice, year, nstock, nfleet, niter) {
    .Call('_MixME_flr_to_list', PACKAGE = 'MixME', om, advice, year, nstock, nfleet, niter)
}

fwd_update_fleets <- function(om, om_fwd, tracking, year, adviceType) {
    .Call('_MixME_fwd_update_fleets', PACKAGE = 'MixME', om, om_fwd, tracking, year, adviceType)
}

